### PR TITLE
Add support for Gone status code (410)

### PR DESCRIPTION
**Pull request by YoranBrondsema**

### CODE REVIEW

**Comment by YoranBrondsema** [comment]
Hmmm the build seems to fail only on the Beta release of Ember.js

````
not ok 34 Chrome 64.0 - AsyncWidgetComponent service injected in component
    ---
        message: >
            Assertion Failed: You attempted to access the `lastObject.volatileSet` property (of authToken,foo). Due to certain internal implementation details of Ember, the `lastObject` property previously contained an internal "descriptor" object (a private API), therefore `lastObject.volatileSet` would have been `function computedPropertyVolatileSet(obj, keyName, value) {     return this._setter.call(obj, keyName, value);   }`. This internal implementation detail was never intended to be a public (or even intimate) API.
            
            This internal implementation detail has now changed and the (still private) "descriptor" object has been relocated to the object's "meta" (also a private API). Soon, accessing `lastObject` on this object will return the computed value (see RFC #281 for more details).
            
            If you are seeing this error, you are likely using an addon that relies on this now-defunct private implementation detail. If you can, find out which addon is doing this from the stack trace below and report this bug to the addon authors. If you feel stuck, the Ember Community Slack (https://ember-community-slackin.herokuapp.com/) may be able to offer some help.
            
            If you are an addon author and need help transitioning your code, please get in touch in the #dev-ember channel in the Ember Community Slack.
        stack: >
            Error: Assertion Failed: You attempted to access the `lastObject.volatileSet` property (of authToken,foo). Due to certain internal implementation details of Ember, the `lastObject` property previously contained an internal "descriptor" object (a private API), therefore `lastObject.volatileSet` would have been `function computedPropertyVolatileSet(obj, keyName, value) {     return this._setter.call(obj, keyName, value);   }`. This internal implementation detail was never intended to be a public (or even intimate) API.
            
            This internal implementation detail has now changed and the (still private) "descriptor" object has been relocated to the object's "meta" (also a private API). Soon, accessing `lastObject` on this object will return the computed value (see RFC #281 for more details).
            
            If you are seeing this error, you are likely using an addon that relies on this now-defunct private implementation detail. If you can, find out which addon is doing this from the stack trace below and report this bug to the addon authors. If you feel stuck, the Ember Community Slack (https://ember-community-slackin.herokuapp.com/) may be able to offer some help.
            
            If you are an addon author and need help transitioning your code, please get in touch in the #dev-ember channel in the Ember Community Slack.
                at new EmberError (http://localhost:7357/assets/vendor.js:24122:25)
                at Object.assert (http://localhost:7357/assets/vendor.js:24365:15)
                at Object.get (http://localhost:7357/assets/vendor.js:33972:42)
                at objectEqual (http://localhost:7357/assets/test-support.js:32391:21)
                at deepEqual (http://localhost:7357/assets/test-support.js:32197:12)
                at objectEqual (http://localhost:7357/assets/test-support.js:32391:10)
                at Object.deepEqual [as eql] (http://localhost:7357/assets/test-support.js:32197:12)
                at Assertion.assertEql (http://localhost:7357/assets/test-support.js:27353:11)
                at Assertion.ctx.(anonymous function) [as eql] (http://localhost:7357/assets/test-support.js:30735:25)
                at Assertion.assertEqual (http://localhost:7357/assets/test-support.js:27317:19)
        Log: |
    ...
````

**Comment by alexlafroscia** [comment]
Yeesh, sorry I've let this sit for so long! Can you rebase the PR off of `master` (which has changed a bit this weekend, just updating to the latest addon blueprint) and we'll get this pulled in. The build shouldn't be failing on `beta` anymore.

**Comment by YoranBrondsema** [comment]
No problem! I just rebased and I see the tests are all green now.

**Comment by alexlafroscia** [comment]
Thanks man! I really appreciate it, and apologize again for the delay here

**Comment by YoranBrondsema** [comment]
No worries, happy to see it merged!

**Pull request merged**
