### PR TITLE
Adds `namespace` option. Fixes #30

### LINKED ISSUE #30: Server API version
As of now, I am using the `host` option to configure the server API version.

```js
// app/services/ajax.js

import Ember from 'ember';
import AjaxService from 'ember-ajax/services/ajax';

export default AjaxService.extend({
  host: '/api/v1'
});

```

Is that ok?

### PR DESCRIPTION
**Pull request by manoharank**
cc @taras @alexlafroscia

### CODE REVIEW

**Comment by manoharank** [comment]
test-fails

3 test cases are failed due to prepending `/` in the url. Either I have to change the url in the tests or have to add more checks [here](https://github.com/ember-cli/ember-ajax/blob/4ef61fb6d39a8c89adeffc63599cd85021115a34/addon/services/ajax.js#L199).

**Comment by manoharank** [comment]
ping @alexlafroscia @taras

**Comment by alexlafroscia** [comment]
@manoharank I'll check this out.  In the meantime, this PR can no longer be pulled cleanly due to the big changes in #42.  If you could update your PR to pass, that would be excellent.  If not, I would be happy to do so, but would probably close this PR and open a new one based off the current `master` branch.

**Comment by alexlafroscia** [comment]
In the commits since this PR was done, I updated a bunch of those tests so that the URLs make a lot more sense.  If you could update your PR based on this stuff, that would be great.  If you can't, that's fine; I can try to fix whatever is broke, and get it merge-able.  I would like to get this in before the 2.0 release since I think it's a really useful change.

**Comment by manoharank** [comment]
I will update PR this evening

**Comment by manoharank** [comment]
@alexlafroscia Three test cases are failed due to the url (`example.com`) without `http` or leading `/`. How can I fix these existing test cases?

Test case failure for `example.com`. This is due to prepending `/` in `_normalizePath`
test-failure-1
 
Test case failure for `http://example.com`. This is due to `a.href`.
test-failure-2

**Comment by alexlafroscia** [comment]
Huh, weird.  I'll check this out and try to fix whatever is going on with the existing tests.  In the meantime, would you mind adding a few new tests to verify the namespace behavior?

Thanks so much for your work on this!

**Comment by alexlafroscia** [comment]
Okay, I see what's going on: since you added the `_normalizePath` method, and the argument there is being interpreted as part of the path, it's adding the `/` to the beginning of the URL.  I think this behavior is fine, personally, since you're not really meant to put a URL in there that doesn't have the protocol specified.  I'm about to push a commit to this PR that fixed that.

**Comment by alexlafroscia** [comment]
Hmm... I have a commit that I want to add to this PR.  I thought that was a think you can do?  @manoharank if you add me as a collaborator on your fork, that should work, but I thought that I was able to push to your fork being a contributor of the original repo.  @taras any thoughts?

**Comment by manoharank** [comment]
@alexlafroscia I have added you as a collaborator. I will add the test cases for `namespace` option.

**Comment by alexlafroscia** [comment]
Great! I pushed the commit, so you should be able to pull that and add your tests.  Once we have that, this PR gets a :+1: from me!  Thanks again for pushing through to get it finished before the 2.0 release.

**Comment by manoharank** [comment]
@alexlafroscia I have added some test cases and docs, check them and let me know if any changes required.

**Comment by alexlafroscia** [comment]
Looks good! The only thing I'm not sure of is whether we want the namespace overwritable on a per-request basis.  What do you think about that @taras?

**Comment by taras** [comment]
@alexlafroscia no, it should be open option for the service - not over writable.

**Comment by manoharank** [comment]
@alexlafroscia @taras I have removed the overwritable option.

**Comment by alexlafroscia** [comment]
I'm good to pull if you are @taras

**Comment by taras** [comment]
@alexlafroscia looks good to me

**Pull request merged**
