### PR TITLE
Migrate from Travis to GitHub Actions

### PR DESCRIPTION
**Pull request by boris-petrov**
By using:
https://github.com/jelhan/create-github-actions-setup-for-ember-addon
And adding a couple more linter steps from the Travis config file

### CODE REVIEW

**Comment by boris-petrov** [comment]
@Turbo87 - here is an initial version. It doesn't seem to run for some reason - perhaps you'll have to enable it in [here](https://github.com/ember-cli/ember-ajax/actions) somehow.

Also, note that this probably will fail again. The CI uses Node 6 which is very old and perhaps that's one of the reasons Travis fails on the other PR.

**Comment by rwjblue** [comment]
> It doesn't seem to run for some reason

GH Actions won't run from a fork

**Comment by boris-petrov** [comment]
@rwjblue - so what do you suggest?

**Comment by rwjblue** [comment]
@boris-petrov - Leave `.travis.yml` (they'll both run then) until we can confirm the GH Actions setup works

**Comment by boris-petrov** [comment]
@rwjblue - did that but GitHub Actions doesn't seem to be running...

**Comment by Turbo87** [comment]
@boris-petrov I tried it with your config, but unfortunately it failed in several way. I've merged a GitHub Actions config now in #459

**Pull request closed without merging**
