### PR TITLE
Make host option overridable

### PR DESCRIPTION
**Pull request by Cryrivers**

### CODE REVIEW

**Comment by stefanpenner** [comment]
sgtm but needs a test

**Comment by Cryrivers** [comment]
will do.

**Comment by Cryrivers** [comment]
@stefanpenner i'll do it.

**Comment by alexlafroscia** [comment]
@Cryrivers are you still planning to add a test for this?  If not, I can write up the test to get this finished up.

**Comment by Cryrivers** [comment]
@alexlafroscia been busy recently. please help me finish the test :) thank you

**Comment by alexlafroscia** [comment]
@Cryrivers Sure thing, I'll take care of it.

**Comment by alexlafroscia** [comment]
@Cryrivers I made a new PR that adds this functionality.  It's broken into two commits; one adds this exact functionality to the new ES6 class, and I credited you as the author of that.  I then added a second commit that adds a test for it.  You can check it out at #44

**Pull request closed without merging**
