### PR TITLE
Add JSCS checking with ember-suave

### PR DESCRIPTION
**Pull request by alexlafroscia**
Also updates all of the code to pass the checks

### CODE REVIEW

**Comment by taras** [comment]
:+1:

**Comment by taras** [comment]
PR looks good, but travis is acting up. My need to push another PR to force it to rerun.

**Comment by alexlafroscia** [comment]
Huh, for some reason `ember test` passes locally but some files were checked on Travis that weren't checked locally... I'll check it out.

**Comment by alexlafroscia** [comment]
Even weirder, the files _are_ checked locally too, but pass locally with `ember test` and fail if you run `jscs` against the file specifically.  And then fail with `ember test` in CI.

**Comment by taras** [comment]
try removing node_modules, bower_components and tmp. Then run `npm install; bower install; ember test`

**Comment by alexlafroscia** [comment]
:ok_hand:

**Pull request merged**
