### PR TITLE
Document stand-alone usage

### LINKED ISSUE #134: Access in utilities
I can't find a way to access ember-ajax inside a utility. Is this possible, if not, why? This requires me to either wrap `Ember.$.ajax` or include `ic-ajax` or some other library. Seems wasteful.

### PR DESCRIPTION
**Pull request by knownasilya**
Fixes #134

### CODE REVIEW

**Comment by alexlafroscia** [comment]
If we're going to mention this in the readme (and I'm worried out readme is getting really bloated) we should do both `request` and `raw`, and explain the difference.

**Comment by knownasilya** [comment]
@alexlafroscia @rwjblue how is this?

**Comment by alexlafroscia** [comment]
Great! Can you just add a little usage example below each import?  Something like

```js
import request from 'ember-ajax/request';

return request('/foo', { ... });
```

and the same for raw.  Just in case someone doesn't know what to do once they have the function.

**Comment by knownasilya** [comment]
Added examples

**Comment by alexlafroscia** [comment]
Thank you!

**Pull request merged**
