### PR TITLE
Fix deprecated usage of `run.join`

### LINKED ISSUE #451: Deprecation warnings with Ember 3.27
Using [run.join](https://github.com/ember-cli/ember-ajax/blob/v5.0.0/addon/mixins/ajax-request.ts#L303) is deprecated in Ember 3.27 and will be removed in Ember 4.

### PR DESCRIPTION
**Pull request by boris-petrov**
Fixes #451.

cc @rwjblue, @Turbo87, @mike-north

### CODE REVIEW

**Review by Turbo87 — APPROVED** [review]
thanks! 👍

**Comment by boris-petrov** [comment]
Can we get this merged and released please? :)

**Comment by Turbo87** [comment]
unfortunately CI failed 😞 

would you have time to port the CI pipeline to GitHub Actions?

**Comment by boris-petrov** [comment]
@Turbo87 - I agree that having a working CI is good but this fix is obviously correct so merging and releasing would be nice. We get lots of warnings in the console which would go away.

There is #453 which is for fixing CI but could we merge this before we resolve the issues with GitHub Actions please?

**Review by Turbo87 — APPROVED** [review]

**Comment by boris-petrov** [comment]
@Turbo87 - thanks for merging this! Now a new release will be very appreciated! :)

**Comment by boris-petrov** [comment]
@rwjblue, @Turbo87, @mike-north - ping. :) Can we get a new release, please? :)

**Comment by boris-petrov** [comment]
@rwjblue, @Turbo87, @mike-north - ping. :) Can we get a new release, please? :)

**Comment by boris-petrov** [comment]
@rwjblue, @Turbo87, @mike-north - ping. :) Can we get a new release, please? :)

**Pull request merged**
