### PR TITLE
Added gitter team chat badge

### PR DESCRIPTION
**Pull request by rajzshkr**

### CODE REVIEW

**Comment by alexlafroscia** [comment]
I talked to @nathanhammond today and we're going to see about making an `e-ajax` channel in the Ember community slack.  If we can get that settled, I'd rather link to that instead. Nathan mentioned that the community is trying to keep everything under one roof, and I'd like to keep in line with that if possible.

If we don't end up making a Slack channel, then he'll help me make a Gitter channel that's properly tied to this Github repo and we'll link to that.

**Comment by rajzshkr** [comment]
yeah, it make sense!!

**Comment by nathanhammond** [comment]
Confirm to all of this. /cc @locks

**Comment by locks** [comment]
Channel created :P

**Comment by alexlafroscia** [comment]
@rajzshkr could you put together a PR with a link to the info on the Ember Community slack and the name of the channel?

**Comment by rajzshkr** [comment]
@alexlafroscia sure!!

**Pull request closed without merging**
