### PR TITLE
Do not remove trailing slashes, when dealing with relative urls.

### PR DESCRIPTION
**Pull request by badazz91**
see #70

### CODE REVIEW

**Comment by alexlafroscia** [comment]
@badazz91 can you add me as a collaborator on your fork? I added a failing test that is introduced by your changes.

**Comment by badazz91** [comment]
@alexlafroscia I added you as a collaborator.

**Comment by alexlafroscia** [comment]
@badazz91 great, thanks.  I added the commit with the failing test.

**Comment by badazz91** [comment]
@alexlafroscia We made some modifications, to satisfy the failing test. Let me know about your thoughts.

**Comment by alexlafroscia** [comment]
I added some more test cases, found a place where they fail again.  I still feel pretty strongly that `_normalizePath` should be left as it was, to ensure that all the segments end up in the same format (`/` at the start, no `/` at the end).  Maybe checking if the full URL has a trailing slash, and then add it back at the end if it needs it?

**Comment by alexlafroscia** [comment]
Closed in favor of #96 which was merged a while back.

**Pull request closed without merging**
