### PR TITLE
Update description

### PR DESCRIPTION
**Pull request by zoltan-nz**
because of emberobserver.com: https://www.emberobserver.com/addons/ember-ajax ;)

### CODE REVIEW

**Comment by alexlafroscia** [comment]
Do you know if there's some way to signal that 1.12 isn't supported anymore, other than doing this?  I feel like the `package.json` description is the wrong place to note this, and that maybe the README would be more appropriate.

**Comment by zoltan-nz** [comment]
EmberObserver uses package.json description line as the default description on the home page. It looks, that package.json description was never updated from default, you can see this on the home page:

image

I just used the first sentence from README.md, it is mainly describe what is this `ember-ajax` addon for. ;)

**Comment by zoltan-nz** [comment]
npmjs.org uses description as subtitle also.

image

**Comment by alexlafroscia** [comment]
Ahh, I see.  This is :thumbsup: from me then!

**Pull request merged**
